# permissions for end users to edit plaintexts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: plaintext-editor-role
rules:
- apiGroups:
  - secret.linhng98.com
  resources:
  - plaintexts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secret.linhng98.com
  resources:
  - plaintexts/status
  verbs:
  - get
